// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.WebAPI.Data;

namespace SmartSchool.WebAPI.Migrations
{
    [DbContext(typeof(SmartContext))]
    [Migration("20200524203614_third")]
    partial class third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Datani")
                        .HasColumnType("datetime2");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataNasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(4740),
                            Matricula = 1,
                            Nome = "Marta",
                            Sobrenome = "Kent",
                            Telefone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataNasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(6391),
                            Matricula = 2,
                            Nome = "Paula",
                            Sobrenome = "Isabela",
                            Telefone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataNasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(6447),
                            Matricula = 3,
                            Nome = "Laura",
                            Sobrenome = "Antonia",
                            Telefone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataNasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(6454),
                            Matricula = 4,
                            Nome = "Luiza",
                            Sobrenome = "Maria",
                            Telefone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataNasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(6458),
                            Matricula = 5,
                            Nome = "Lucas",
                            Sobrenome = "Machado",
                            Telefone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataNasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(6466),
                            Matricula = 6,
                            Nome = "Pedro",
                            Sobrenome = "Alvares",
                            Telefone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataNasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(6471),
                            Matricula = 7,
                            Nome = "Paulo",
                            Sobrenome = "José",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Datani")
                        .HasColumnType("datetime2");

                    b.HasKey("AlunoId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("AlunosCursos");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Datani")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Nota")
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(7756)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8279)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8310)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8312)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8313)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8317)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8319)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8320)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8322)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8324)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8326)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8327)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8328)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8329)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8331)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8332)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8333)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8336)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8337)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8338)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8340)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8341)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 305, DateTimeKind.Local).AddTicks(8342)
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Sistemas de Informação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ciência da Computação"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrerequisitoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("PrerequisitoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 5,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 6,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 7,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 8,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 9,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 10,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Datani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Registro")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 300, DateTimeKind.Local).AddTicks(6202),
                            Nome = "Lauro",
                            Registro = 1,
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 301, DateTimeKind.Local).AddTicks(8854),
                            Nome = "Roberto",
                            Registro = 2,
                            Sobrenome = "Soares"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 301, DateTimeKind.Local).AddTicks(8920),
                            Nome = "Ronaldo",
                            Registro = 3,
                            Sobrenome = "Marconi"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 301, DateTimeKind.Local).AddTicks(8923),
                            Nome = "Rodrigo",
                            Registro = 4,
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Datani = new DateTime(2020, 5, 24, 17, 36, 13, 301, DateTimeKind.Local).AddTicks(8924),
                            Nome = "Alexandre",
                            Registro = 5,
                            Sobrenome = "Montanha"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoCurso", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Disciplina", "Prerequisito")
                        .WithMany()
                        .HasForeignKey("PrerequisitoId");

                    b.HasOne("SmartSchool.WebAPI.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
